# Sources data

# --- !Ups

insert into sources(section, url) values('news', 'http://rss.slashdot.org/Slashdot/slashdotMainatom');
insert into sources(section, url) values('news', 'http://feeds.feedburner.com/TechCrunch/');
insert into sources(section, url) values('news', 'http://www.wired.com/feed/');
insert into sources(section, url) values('news', 'https://news.ycombinator.com/rss');
insert into sources(section, url) values('news', 'http://feeds2.feedburner.com/thenextweb');
insert into sources(section, url) values('news', 'http://feeds.mashable.com/Mashable');
insert into sources(section, url) values('news', 'http://feeds.dzone.com/home');
insert into sources(section, url) values('news', 'https://www.infoq.com/feed');
insert into sources(section, url) values('news', 'http://www.cnet.com/rss/all/');
insert into sources(section, url) values('news', 'http://www.engadget.com/rss.xml');
insert into sources(section, url) values('news', 'http://www.techmeme.com/feed.xml');
insert into sources(section, url) values('news', 'http://www.pulseheadlines.com/headlines/technology/feed/');
insert into sources(section, url) values('news', 'http://feeds.feedburner.com/neowin-main');
insert into sources(section, url) values('news', 'http://www.computerworld.com/index.rss');
insert into sources(section, url) values('news', 'http://feeds.feedburner.com/venturebeat/SZYF');
insert into sources(section, url) values('news', 'http://www.pulseheadlines.com/headlines/science/feed/');
insert into sources(section, url) values('news', 'http://feeds.arstechnica.com/arstechnica/index/');
insert into sources(section, url) values('news', 'https://www.smashingmagazine.com/feed/');
insert into sources(section, url) values('news', 'http://www.theregister.co.uk/headlines.atom');
insert into sources(section, url) values('news', 'http://www.theonion.com/feeds/rss');
insert into sources(section, url) values('news', 'http://feeds.feedburner.com/nymag/selectall');
insert into sources(section, url) values('news', 'http://www.theverge.com/rss/full.xml');
insert into sources(section, `group`, url) values('news', 'digg', 'http://digg.com/channel/technology.rss');
insert into sources(section, `group`, url) values('news', 'digg', 'http://digg.com/channel/science.rss');
insert into sources(section, `group`, url) values('news', 'reddit', 'https://www.reddit.com/r/programming/.rss');
insert into sources(section, `group`, url) values('news', 'reddit', 'https://www.reddit.com/r/technology/.rss');
insert into sources(section, `group`, url) values('news', 'reddit', 'https://www.reddit.com/r/coding/.rss');
insert into sources(section, `group`, url) values('news', 'reddit', 'https://www.reddit.com/r/algorithms/.rss');
insert into sources(section, `group`, url) values('news', 'zdnet', 'http://www.zdnet.com/blog/rss.xml');
insert into sources(section, `group`, url) values('news', 'zdnet', 'http://www.zdnet.com/news/rss.xml');
insert into sources(section, `group`, url) values('news', 'gawker', 'http://feeds.gawker.com/lifehacker/full');
insert into sources(section, `group`, url) values('news', 'gawker', 'http://feeds.gawker.com/gizmodo/full');
insert into sources(section, `group`, url) values('news', 'medium', 'https://medium.com/feed/tag/tech');
insert into sources(section, `group`, url) values('news', 'medium', 'https://medium.com/feed/tag/technology');
insert into sources(section, `group`, url) values('news', 'medium', 'https://medium.com/feed/tag/artificial-intelligence');
insert into sources(section, `group`, url) values('news', 'medium', 'https://medium.com/feed/tag/virtual-reality');
insert into sources(section, `group`, url) values('news', 'medium', 'https://medium.com/feed/tag/space');
insert into sources(section, `group`, url) values('news', 'medium', 'https://medium.com/feed/tag/social-media');
insert into sources(section, `group`, url) values('news', 'medium', 'https://medium.com/feed/tag/self-driving-cars');
insert into sources(section, `group`, url) values('news', 'medium', 'https://medium.com/feed/tag/privacy');
insert into sources(section, `group`, url) values('news', 'medium', 'https://medium.com/feed/tag/internet-of-things');
insert into sources(section, `group`, url) values('news', 'medium', 'https://medium.com/feed/tag/innovation');
insert into sources(section, `group`, url) values('news', 'medium', 'https://medium.com/feed/tag/ideas');
insert into sources(section, `group`, url) values('news', 'medium', 'https://medium.com/feed/tag/future');
insert into sources(section, `group`, url) values('news', 'medium', 'https://medium.com/feed/tag/design');
insert into sources(section, `group`, url) values('news', 'medium', 'https://medium.com/feed/tag/artificial-intelligence');
insert into sources(section, `group`, url) values('news', 'medium', 'https://medium.com/feed/tag/apps');
insert into sources(section, `group`, url) values('news', 'medium', 'https://medium.com/feed/tag/bitcoin');
insert into sources(active, section, url) values(false, 'news', 'https://www.newscientist.com/feed/home?cmpid=RSS%7CNSNS-Home&utm_medium=RSS&utm_source=NSNS&utm_campaign=Home&utm_content=Home');
insert into sources(section, url) values('news', 'http://www.sciencemag.org/rss/news_current.xml');
insert into sources(section, url) values('news', 'https://www.sciencenews.org/feeds/headlines.rss');
insert into sources(section, url) values('news', 'http://www.comingsoon.net/feed');

insert into sources(section, url) values('blogs.personal', 'http://buransky.com/feed/');
insert into sources(section, url) values('blogs.personal', 'http://martinfowler.com/feed.atom');
insert into sources(section, url) values('blogs.personal', 'https://feeds.feedburner.com/codinghorror');
insert into sources(section, url) values('blogs.personal', 'http://raganwald.com/rss.xml');
insert into sources(section, url) values('blogs.personal', 'https://henrikwarne.com/feed/');
insert into sources(section, url) values('blogs.personal', 'http://keaplogik.blogspot.com/feeds/posts/default');
insert into sources(section, url) values('blogs.personal', 'http://insightfullogic.com/atom');
insert into sources(section, url) values('blogs.personal', 'http://feeds.feedburner.com/MarginallyInteresting');
insert into sources(section, url) values('blogs.personal', 'http://feeds.feedburner.com/juristrumpflohner');
insert into sources(section, url) values('blogs.personal', 'http://feeds2.feedburner.com/MarkNeedham');
insert into sources(section, url) values('blogs.personal', 'http://feeds.feedburner.com/InspiredByActualEvents');
insert into sources(section, url) values('blogs.personal', 'http://matteo.vaccari.name/blog/feed');
insert into sources(section, url) values('blogs.personal', 'https://cumulative-hypotheses.org/feed/');
insert into sources(section, url) values('blogs.personal', 'http://www.joelonsoftware.com/rss.xml');
insert into sources(section, url) values('blogs.personal', 'http://feeds.feedblitz.com/PetriKainulainen');
insert into sources(section, url) values('blogs.personal', 'http://mechanical-sympathy.blogspot.com/feeds/posts/default');
insert into sources(section, url) values('blogs.personal', 'https://www.schneier.com/blog/atom.xml');
insert into sources(section, url) values('blogs.personal', 'http://feeds.feedburner.com/danielwestheide');
insert into sources(section, url) values('blogs.personal', 'http://feeds.codecommit.com/codecommit');
insert into sources(section, url) values('blogs.personal', 'http://feeds.feedburner.com/RuminationsOfAProgrammer');
insert into sources(section, url) values('blogs.personal', 'http://blog.getbootstrap.com/feed.xml');
insert into sources(section, url) values('blogs.personal', 'https://www.triplet.fi/blog/rss/');
insert into sources(section, url) values('blogs.personal', 'http://feeds.feedburner.com/planningforaliens');
insert into sources(section, url) values('blogs.personal', 'https://zedshaw.com/feed/');
insert into sources(section, url) values('blogs.personal', 'http://feeds.feedburner.com/html5rocks');
insert into sources(section, url) values('blogs.personal', 'https://jakearchibald.com/posts.rss');
insert into sources(section, url) values('blogs.personal', 'https://infrequently.org/feed/');
insert into sources(section, url) values('blogs.personal', 'https://trib.tv/feed/');
insert into sources(section, url) values('blogs.personal', 'https://www.kryogenix.org/days/feed');
insert into sources(section, url) values('blogs.personal', 'http://justmarkup.com/log/feed/');
insert into sources(section, url) values('blogs.personal', 'http://dcsobral.blogspot.com/feeds/posts/default');
insert into sources(section, url) values('blogs.personal', 'https://labs.spotify.com/feed/');
insert into sources(section, url) values('blogs.personal', 'http://perevillega.com/feed.xml');
insert into sources(section, url) values('blogs.personal', 'http://flyingfrogblog.blogspot.com/feeds/posts/default');
insert into sources(section, url) values('blogs.personal', 'http://rerun.me/rss/');
insert into sources(section, url) values('blogs.personal', 'https://javax0.wordpress.com/feed/');
insert into sources(section, url) values('blogs.personal', 'http://feeds.feedburner.com/softwarecraft');
insert into sources(section, url) values('blogs.personal', 'https://scotch.io/feed');
insert into sources(section, url) values('blogs.personal', 'http://joelgrus.com/feeds/atom.xml');
insert into sources(section, url) values('blogs.personal', 'http://melix.github.io/blog/');
insert into sources(section, url) values('blogs.personal', 'http://jvns.ca/atom.xml');
insert into sources(section, url) values('blogs.personal', 'https://josipbakic.wordpress.com/feed/');
insert into sources(section, url) values('blogs.personal', 'http://movingfulcrum.com/rss/');
insert into sources(section, url) values('blogs.personal', 'http://ethanjoachimeldridge.info/tech-blog/feed.xml');

insert into sources(section, `group`, url) values('blogs.org', 'javaworld', 'http://www.javaworld.com/blog/cool-tools-jw/index.rss');
insert into sources(section, `group`, url) values('blogs.org', 'javaworld', 'http://www.javaworld.com/blog/design-techniques/index.rss');
insert into sources(section, `group`, url) values('blogs.org', 'javaworld', 'http://www.javaworld.com/blog/dustins-software-development-cogitations-and-speculations/index.rss');
insert into sources(section, `group`, url) values('blogs.org', 'javaworld', 'http://www.javaworld.com/blog/how-to-java/index.rss');
insert into sources(section, `group`, url) values('blogs.org', 'javaworld', 'http://www.javaworld.com/blog/javabeans-column/index.rss');
insert into sources(section, `group`, url) values('blogs.org', 'javaworld', 'http://www.javaworld.com/blog/java-design-patterns/index.rss');
insert into sources(section, `group`, url) values('blogs.org', 'javaworld', 'http://www.javaworld.com/blog/java-developer/index.rss');
insert into sources(section, `group`, url) values('blogs.org', 'javaworld', 'http://www.javaworld.com/blog/java-fun-and-games/index.rss');
insert into sources(section, `group`, url) values('blogs.org', 'javaworld', 'http://www.javaworld.com/blog/java-indepth/index.rss');
insert into sources(section, `group`, url) values('blogs.org', 'javaworld', 'http://www.javaworld.com/blog/java-qanda/index.rss');
insert into sources(section, `group`, url) values('blogs.org', 'javaworld', 'http://www.javaworld.com/blog/javascript-column/index.rss');
insert into sources(section, `group`, url) values('blogs.org', 'javaworld', 'http://www.javaworld.com/blog/java-tips/index.rss');
insert into sources(section, `group`, url) values('blogs.org', 'javaworld', 'http://www.javaworld.com/blog/java-toolbox/index.rss');
insert into sources(section, `group`, url) values('blogs.org', 'javaworld', 'http://www.javaworld.com/blog/java-traps/index.rss');
insert into sources(section, `group`, url) values('blogs.org', 'javaworld', 'http://www.javaworld.com/blog/jw-soapbox/index.rss');
insert into sources(section, `group`, url) values('blogs.org', 'javaworld', 'http://www.javaworld.com/blog/media-programming/index.rss');
insert into sources(section, url) values('blogs.org', 'http://feeds.feedburner.com/cloudfour');
insert into sources(section, url) values('blogs.org', 'http://thescalawags.libsyn.com/rss');
insert into sources(section, url) values('blogs.org', 'http://blog.takipi.com/feed/');
insert into sources(section, url) values('blogs.org', 'https://plumbr.eu/feed');
insert into sources(section, url) values('blogs.org', 'https://www.lightbend.com/blog/rss.xml');
insert into sources(section, url) values('blogs.org', 'http://feeds.feedburner.com/JavaCodeGeeks');
insert into sources(section, url) values('blogs.org', 'http://www.cakesolutions.net/teamblogs/rss.xml');
insert into sources(section, url) values('blogs.org', 'https://www.hakkalabs.co/feed');
insert into sources(section, url) values('blogs.org', 'http://blog.scalac.io/feeds/index.xml');
insert into sources(section, url) values('blogs.org', 'http://techblog.netflix.com/feeds/posts/default');
insert into sources(section, url) values('blogs.org', 'http://feeds.feedburner.com/alistapart/main');
insert into sources(section, url) values('blogs.org', 'http://feeds.feedburner.com/CssTricks');
insert into sources(section, url) values('blogs.org', 'https://blog.twitter.com/api/blog.rss?name=engineering');
insert into sources(section, url) values('blogs.org', 'http://dev.sortable.com/feed.xml');
insert into sources(section, url) values('blogs.org', 'http://feeds.feedblitz.com/atomicspin');
insert into sources(section, url) values('blogs.org', 'https://code.facebook.com/posts/rss');
insert into sources(section, url) values('blogs.org', 'https://medium.freecodecamp.com/feed');
insert into sources(section, url) values('blogs.org', 'http://blog.xebia.com/feed/');

insert into sources(section, url) values('blogs.product', 'http://blog.jquery.com/feed/');
insert into sources(section, url) values('blogs.product', 'https://facebook.github.io/react/feed.xml');
insert into sources(section, url) values('blogs.product', 'http://blogs.aws.amazon.com/security/blog/feed/recentPosts.rss');
insert into sources(section, url) values('blogs.product', 'http://blogs.aws.amazon.com/bigdata/blog/feed/recentPosts.rss');
insert into sources(section, url) values('blogs.product', 'http://angularjs.blogspot.com/feeds/posts/default');
insert into sources(section, url) values('blogs.product', 'https://www.awsarchitectureblog.com/atom.xml');
insert into sources(section, url) values('blogs.product', 'http://feeds.feedburner.com/ClPlBl');
insert into sources(section, url) values('blogs.product', 'http://java.awsblog.com/blog/feed/recentPosts.rss');
insert into sources(section, url) values('blogs.product', 'http://info.meteor.com/blog/rss.xml');
insert into sources(section, url) values('blogs.product', 'https://articles.fortawesome.com/feed');
insert into sources(section, url) values('blogs.product', 'https://blog.creativecommons.org/feed/');
insert into sources(section, url) values('blogs.product', 'https://github.com/blog.atom');
insert into sources(section, url) values('blogs.product', 'https://www.jetbrains.com/rss.xml');
insert into sources(section, url, `site_url`) values('blogs.product', 'http://feeds2.feedburner.com/heroku', 'https://blog.heroku.com/');
insert into sources(section, url) values('blogs.product', 'https://blog.docker.com/feed/');
insert into sources(section, url, `title`) values('blogs.product', 'http://www.scala-lang.org/feed/blog.xml', 'The Scala Language');
insert into sources(section, url) values('blogs.product', 'https://blogs.apache.org/foundation/feed/entries/atom');
insert into sources(section, url) values('blogs.product', 'http://gradle.org/feed/');
insert into sources(section, url) values('blogs.product', 'https://blog.jooq.org/feed/');

# --- !Downs

delete from sources;
